title: My-New-Test-Page
author: Miraal817
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first page, this is a work in progress.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  miraal817 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
